import type { ProductCategory } from "./types";

// ────────────────────────────────────────────────────────────
// GENERADO por scripts/compose-collections.mjs — no editar a mano.
// Páginas de colección SEO por tipo de equipo. eyebrow/h1/keywords salen del
// research (scripts/keyword-research.mjs); slug/label/intro son curados.
// ────────────────────────────────────────────────────────────

export type Collection = {
  slug: string;
  type: string;
  category: ProductCategory;
  label: string;
  eyebrow: string;
  h1: string;
  intro: string;
  keywords: string[];
  sortOrder: number;
};

export const COLLECTIONS: Collection[] = [
  {
    "slug": "granizadoras-industriales",
    "type": "granizadora",
    "category": "bebidas",
    "label": "Granizadoras industriales",
    "eyebrow": "granizadora industrial",
    "h1": "Granizadora industrial para vender raspados y cholados todo el día",
    "intro": "Equipos para vender raspados, cholados y frappés con textura cremosa todo el día. Elige entre 1, 2 o 3 tanques según la rotación de tu negocio.",
    "keywords": [
      "granizadora industrial",
      "máquina granizadora",
      "granizadora 2 tanques",
      "granizadora 3 tanques 12 litros",
      "máquina para granizados",
      "máquina de raspados",
      "máquina para raspados y cholados",
      "granizadora precio",
      "granizadora industrial bogotá",
      "granizadora comercial",
      "máquina de granizados precio colombia"
    ],
    "sortOrder": 1
  },
  {
    "slug": "licuadoras-industriales",
    "type": "licuadora",
    "category": "bebidas",
    "label": "Licuadoras industriales",
    "eyebrow": "licuadora industrial",
    "h1": "Licuadora industrial de alto rendimiento para procesar a toda hora sin recalentarse",
    "intro": "Motores de alto rendimiento que trituran hielo y fruta congelada sin recalentarse, turno tras turno. Para barras de jugos, cafeterías y restaurantes.",
    "keywords": [
      "licuadora industrial",
      "licuadora industrial 4 litros",
      "licuadora industrial 2 litros",
      "licuadora semi industrial",
      "licuadora comercial",
      "licuadora industrial acero inoxidable",
      "licuadora para restaurante",
      "licuadora industrial precio",
      "licuadora industrial bogotá",
      "licuadora industrial alto rendimiento",
      "licuadora industrial 2.9 hp"
    ],
    "sortOrder": 2
  },
  {
    "slug": "exprimidores-de-naranja",
    "type": "exprimidor",
    "category": "bebidas",
    "label": "Exprimidores de naranja",
    "eyebrow": "exprimidor de naranjas industrial",
    "h1": "Exprimidor de naranjas industrial: jugo natural exprimido en segundos, sin pausas",
    "intro": "Jugo de naranja recién exprimido frente al cliente: modelos manuales, semiautomáticos y automáticos de uso comercial.",
    "keywords": [
      "exprimidor de naranjas industrial",
      "exprimidor de naranjas",
      "exprimidor de naranjas eléctrico",
      "exprimidor de naranjas industrial precio",
      "exprimidor de naranjas industrial bogotá",
      "exprimidor de cítricos comercial",
      "exprimidor de naranjas semiautomático",
      "exprimidor de naranjas profesional",
      "máquina de jugo de naranja",
      "exprimidor naranjas eléctrico industrial",
      "exprimidor de naranjas acero inoxidable"
    ],
    "sortOrder": 3
  },
  {
    "slug": "capuchineras-maquinas-de-cafe",
    "type": "espresso",
    "category": "bebidas",
    "label": "Capuchineras",
    "eyebrow": "capuchinera",
    "h1": "Capuchinera industrial: máquina de café espresso profesional para tu cafetería",
    "intro": "Máquinas de café espresso de 1 y 2 grupos para servir capuchinos y lattes con calidad de barista en tu cafetería.",
    "keywords": [
      "capuchinera",
      "capuchinera industrial",
      "capuchinera profesional",
      "máquina de café espresso",
      "máquina de café 2 grupos",
      "capuchinera 1 grupo",
      "cafetera espresso profesional",
      "máquina espresso para cafetería",
      "capuchinera precio colombia",
      "capuchinera bogotá",
      "capuchinera semiautomática",
      "máquina de café para negocio"
    ],
    "sortOrder": 4
  },
  {
    "slug": "maquinas-de-cafe-automaticas",
    "type": "cafe-automatica",
    "category": "bebidas",
    "label": "Máquinas de café automáticas",
    "eyebrow": "máquina de café automática",
    "h1": "Máquina de café automática para oficina: café a un botón con varias bebidas",
    "intro": "Café a un botón para oficinas y autoservicio: varias bebidas programadas sin necesidad de barista.",
    "keywords": [
      "máquina de café automática",
      "máquina de café para oficina",
      "máquina de café vending",
      "dispensador de café automático",
      "máquina de café automática precio",
      "máquina de café superautomática",
      "máquina vending café colombia",
      "máquina de café a un botón",
      "máquina de café automática empresas",
      "dispensador de bebidas calientes"
    ],
    "sortOrder": 5
  },
  {
    "slug": "selladoras-de-vasos",
    "type": "selladora-vasos",
    "category": "bebidas",
    "label": "Selladoras de vasos",
    "eyebrow": "selladora de vasos",
    "h1": "Selladora de vasos automática: sella tu bubble tea, jugos y granizados para llevar en segundos",
    "intro": "Sella bubble tea, jugos y granizados para llevar sin derrames y con acabado profesional. Modelos manuales y automáticos.",
    "keywords": [
      "selladora de vasos",
      "selladora de vasos automatica",
      "selladora de vasos manual",
      "maquina selladora de vasos",
      "selladora de vasos precio",
      "selladora de vasos colombia",
      "selladora de vasos bogota",
      "termoselladora de vasos",
      "selladora para bubble tea",
      "selladora de vasos para jugos",
      "selladora de vasos industrial",
      "selladora de vasos plasticos"
    ],
    "sortOrder": 6
  },
  {
    "slug": "dispensadores-de-bebidas",
    "type": "dispensador",
    "category": "bebidas",
    "label": "Dispensadores de bebidas",
    "eyebrow": "dispensador de bebidas frias",
    "h1": "Dispensador de bebidas frías de 3 tanques: exhibe y vende jugos refrigerados todo el día",
    "intro": "Exhibe y sirve jugos y bebidas frías en movimiento para autoservicio, eventos y catering.",
    "keywords": [
      "dispensador de bebidas frias",
      "dispensador de jugos",
      "dispensador de bebidas 3 tanques",
      "dispensador de jugos industrial",
      "dispensador de bebidas precio",
      "dispensador de bebidas frias colombia",
      "dispensador de jugos electrico",
      "dispensador de bebidas 2 tanques",
      "dispensador de jugos y bebidas frias",
      "surtidor de jugos",
      "dispensador de jugos bogota",
      "maquina dispensadora de jugos"
    ],
    "sortOrder": 7
  },
  {
    "slug": "trituradoras-de-hielo",
    "type": "trituradora",
    "category": "bebidas",
    "label": "Trituradoras de hielo",
    "eyebrow": "trituradora de hielo",
    "h1": "Trituradora de hielo industrial con bodega: hielo picado al instante para tu negocio",
    "intro": "Hielo picado al instante y sin interrupciones para granizados, cócteles y bebidas frías.",
    "keywords": [
      "trituradora de hielo",
      "triturador de hielo industrial",
      "trituradora de hielo industrial",
      "máquina para triturar hielo",
      "trituradora de hielo comercial",
      "trituradora de hielo con bodega",
      "trituradora de hielo precio",
      "picadora de hielo industrial",
      "trituradora de hielo colombia",
      "triturador de hielo grande",
      "máquina trituradora de hielo"
    ],
    "sortOrder": 8
  },
  {
    "slug": "maquinas-de-hielo",
    "type": "fabricadora",
    "category": "bebidas",
    "label": "Máquinas de hielo",
    "eyebrow": "máquina de hielo",
    "h1": "Máquina de hielo industrial en cubo: fabrica hasta 90 kg al día para tu negocio",
    "intro": "Producción autónoma de hielo en cubo para bares, restaurantes y negocios de bebidas que no pueden quedarse sin hielo.",
    "keywords": [
      "máquina de hielo",
      "fabricadora de hielo",
      "máquina de hielo industrial",
      "máquina para hacer hielo",
      "fabricadora de hielo en cubo",
      "máquina de hielo en cubos",
      "máquina de hielo 90kg",
      "fabricadora de hielo precio",
      "máquina de hielo colombia",
      "productora de hielo industrial",
      "máquina para hacer hielo industrial",
      "máquina de hielo para negocio"
    ],
    "sortOrder": 9
  },
  {
    "slug": "freidoras-industriales",
    "type": "freidora",
    "category": "snacks",
    "label": "Freidoras industriales",
    "eyebrow": "freidora industrial",
    "h1": "Freidora industrial a gas y eléctrica: más capacidad, más ventas por turno",
    "intro": "Fritura rápida y pareja para papas, pollo y apanados. A gas y eléctricas, de uno o dos tanques, para alto volumen.",
    "keywords": [
      "freidora industrial",
      "freidora a gas",
      "freidora industrial a gas",
      "freidora industrial 2 tanques",
      "freidora de papas",
      "freidor industrial",
      "freidora eléctrica doble tanque",
      "freidora industrial precio",
      "freidora industrial colombia",
      "freidora a gas de piso",
      "freidora industrial bogotá",
      "freidora industrial 30 litros"
    ],
    "sortOrder": 10
  },
  {
    "slug": "crispeteras",
    "type": "crispetera",
    "category": "snacks",
    "label": "Crispeteras",
    "eyebrow": "crispetera",
    "h1": "Crispetera con carro y oil free: monta tu negocio de crispetas con margen alto",
    "intro": "Monta tu negocio de crispetas con margen alto: con carro, oil free y de mostrador.",
    "keywords": [
      "crispetera",
      "máquina de crispetas",
      "crispetera con carro",
      "crispetera industrial",
      "crispetera oil free",
      "crispetera sin aceite",
      "máquina de palomitas",
      "crispetera precio",
      "crispetera 8 onzas",
      "crispetera colombia",
      "carro crispetero",
      "crispetera para negocio"
    ],
    "sortOrder": 11
  },
  {
    "slug": "maquinas-de-algodon-de-azucar",
    "type": "algodonera",
    "category": "snacks",
    "label": "Máquinas de algodón de azúcar",
    "eyebrow": "máquina de algodón de azúcar",
    "h1": "Máquina de algodón de azúcar con carro: conos para eventos y negocio de alto margen",
    "intro": "Algodón de azúcar de alta rotación para eventos, fiestas infantiles, parques y kioscos. Con carro o de mesa.",
    "keywords": [
      "máquina de algodón de azúcar",
      "algodonera",
      "máquina de algodón de azúcar industrial",
      "algodonera con carro",
      "máquina de algodón de azúcar precio",
      "máquina de algodón de azúcar bogotá",
      "algodonera comercial",
      "máquina algodón azúcar colombia",
      "algodonera para negocio",
      "máquina de algodones",
      "algodonera manual",
      "máquina de algodón de azúcar para eventos"
    ],
    "sortOrder": 12
  },
  {
    "slug": "asadores-de-salchichas",
    "type": "asador-salchichas",
    "category": "snacks",
    "label": "Asadores de salchichas",
    "eyebrow": "asador de salchichas",
    "h1": "Asador de salchichas de rodillos: vende más perros calientes con rotación constante",
    "intro": "Exhibe y mantén salchichas siempre listas para vender más perros calientes. Modelos de 5 a 11 rodillos.",
    "keywords": [
      "asador de salchichas",
      "asador de salchichas rodillos",
      "asador de salchichas 11 rodillos",
      "asador de salchichas precio",
      "asador de salchichas colombia",
      "máquina de perros calientes",
      "rodillo para salchichas",
      "salchichera comercial",
      "asador de salchichas giratorio",
      "vaporizador de salchichas y panes",
      "asador de salchichas bogotá"
    ],
    "sortOrder": 13
  },
  {
    "slug": "fuentes-de-chocolate",
    "type": "chocolate",
    "category": "snacks",
    "label": "Fuentes y fundidoras de chocolate",
    "eyebrow": "fuente de chocolate",
    "h1": "Fuentes y fundidoras de chocolate: atrae clientes con postres que se venden solos",
    "intro": "Chocolate fundido que vuelve irresistible tu menú: fuentes de cascada por niveles y fundidoras para producción.",
    "keywords": [
      "fuente de chocolate",
      "fuente de chocolate precio",
      "fuente de chocolate comercial",
      "fuente de chocolate 5 niveles",
      "fundidora de chocolate",
      "fundidor de chocolate eléctrico",
      "fuente de chocolate colombia",
      "fuente de chocolate para eventos",
      "fundidora de chocolate 1 tanque",
      "fuente de chocolate bogotá",
      "fuente de chocolate industrial",
      "máquina derretidora de chocolate"
    ],
    "sortOrder": 14
  },
  {
    "slug": "wafleras-industriales",
    "type": "wafflera",
    "category": "snacks",
    "label": "Wafleras industriales",
    "eyebrow": "wafflera industrial",
    "h1": "Wafleras industriales tradicional, burbuja y 2 puestos: waffles listos para vender",
    "intro": "Waffles recién hechos que llenan tu local: tradicional, de burbuja y de varios puestos.",
    "keywords": [
      "wafflera industrial",
      "waflera industrial",
      "máquina de waffles industrial",
      "wafflera",
      "wafflera comercial",
      "wafflera precio",
      "wafflera burbuja",
      "wafflera 2 puestos",
      "máquina de waffles colombia",
      "wafflera tradicional",
      "máquina para hacer waffles",
      "wafflera para negocio"
    ],
    "sortOrder": 15
  },
  {
    "slug": "hornos-industriales",
    "type": "horno",
    "category": "panaderia",
    "label": "Hornos industriales",
    "eyebrow": "horno para panadería",
    "h1": "Hornos industriales para panadería: gas, eléctricos, de convección y pizza — hornea más en cada tanda",
    "intro": "Horneado parejo y constante para pan, pizza y repostería: hornos a gas, eléctricos, de convección y de pizza.",
    "keywords": [
      "horno para panadería",
      "horno industrial para panadería",
      "horno de panadería a gas",
      "horno de panadería eléctrico",
      "horno de convección",
      "horno de convección 4 bandejas",
      "horno de pizza",
      "horno de pizza eléctrico doble cámara",
      "horno panadería 3 cámaras 6 latas",
      "horno industrial precio colombia",
      "horno para panadería precio bogotá",
      "horno comercial acero inoxidable"
    ],
    "sortOrder": 16
  },
  {
    "slug": "amasadoras-industriales",
    "type": "amasadora",
    "category": "panaderia",
    "label": "Amasadoras industriales",
    "eyebrow": "amasadora industrial",
    "h1": "Amasadoras industriales para panadería: 20 y 50 libras que amasan más pan en menos tiempo",
    "intro": "Masa consistente y sin esfuerzo, de 20 a 50 libras, para panaderías y pizzerías que amasan a diario.",
    "keywords": [
      "amasadora industrial",
      "amasadora para panadería",
      "amasadora de pan industrial",
      "amasadora 50 libras",
      "amasadora mojadora 50 libras",
      "amasadora 20 libras",
      "amasadora industrial 3 hp",
      "amasadora industrial 110v",
      "amasadora de pan precio colombia",
      "amasadora para panadería bogotá",
      "amasadora acero inoxidable",
      "amasadora 20 kg"
    ],
    "sortOrder": 17
  },
  {
    "slug": "batidoras-industriales",
    "type": "batidora",
    "category": "panaderia",
    "label": "Batidoras industriales",
    "eyebrow": "batidora industrial",
    "h1": "Batidoras industriales y planetarias: de mesa 7L a pedestal 30L para repostería sin límites",
    "intro": "Cremas y mezclas perfectas batido tras batido: de mesa y de pedestal, para repostería y pastelería.",
    "keywords": [
      "batidora industrial",
      "batidora industrial para repostería",
      "batidora de pedestal",
      "batidora planetaria",
      "batidora industrial 7 litros",
      "batidora industrial 30 litros",
      "batidora para pastelería",
      "batidora para panadería",
      "batidora de mesa",
      "batidora industrial precio colombia",
      "batidora industrial acero inoxidable",
      "batidora profesional 12 velocidades"
    ],
    "sortOrder": 18
  },
  {
    "slug": "empacadoras-al-vacio",
    "type": "empacadora",
    "category": "empaque",
    "label": "Empacadoras al vacío",
    "eyebrow": "empacadora al vacío",
    "h1": "Empacadora al vacío industrial: conserva tus alimentos mucho más tiempo y reduce mermas",
    "intro": "Conserva tus alimentos mucho más tiempo y reduce mermas con sellado al vacío de uso comercial.",
    "keywords": [
      "empacadora al vacío",
      "empacadora al vacío industrial",
      "empacadora al vacío precio",
      "empacadora al vacío dz300",
      "empacadora al vacío doble campana",
      "selladora al vacío",
      "máquina selladora al vacío",
      "empacadora al vacío bogotá",
      "empacadora al vacío para alimentos",
      "máquina de empaque al vacío comercial",
      "empacadora al vacío carnes",
      "empacadora al vacío de campana"
    ],
    "sortOrder": 19
  },
  {
    "slug": "selladoras-de-bolsas",
    "type": "selladora-bolsas",
    "category": "empaque",
    "label": "Selladoras de bolsas",
    "eyebrow": "selladora de bolsas",
    "h1": "Selladora de bolsas profesional: sellado hermético y limpio para empacar más rápido",
    "intro": "Sellado hermético y limpio para empacar granos, snacks y alimentos: manuales, de pedal y de banda continua.",
    "keywords": [
      "selladora de bolsas",
      "selladora de bolsas precio",
      "selladora de bolsas de pedal",
      "selladora de bolsas plásticas",
      "selladora de banda continua",
      "selladora de bolsas industrial",
      "selladora de bolsas 30cm",
      "selladora de pedal 45cm",
      "selladora banda continua con impresión",
      "selladora de bolsas bogotá",
      "máquina selladora de bolsas",
      "selladora de bolsas manual"
    ],
    "sortOrder": 20
  },
  {
    "slug": "rollos-y-consumibles-de-empaque",
    "type": "consumible-empaque",
    "category": "empaque",
    "label": "Rollos y consumibles",
    "eyebrow": "rollos para empacadora al vacío",
    "h1": "Rollos y film para empacadora al vacío: insumos grado alimenticio que rinden más por sello",
    "intro": "Rollos al vacío y sellos para vasos compatibles con tus equipos, grado alimenticio y de alto rendimiento.",
    "keywords": [
      "rollos para empacadora al vacío",
      "rollos para selladora al vacío",
      "rollo empacadora al vacío 25cm",
      "rollos para selladora de vasos",
      "rollo film para selladora de vasos",
      "film para empaque",
      "rollos repuesto empacadora al vacío",
      "rollos para selladora de vasos precio",
      "sello para vasos",
      "bolsas para empacadora al vacío",
      "rollos para empacar al vacío colombia"
    ],
    "sortOrder": 21
  },
  {
    "slug": "basculas-digitales",
    "type": "bascula",
    "category": "pesaje",
    "label": "Básculas digitales",
    "eyebrow": "báscula digital",
    "h1": "Básculas digitales calibradas: pesa con precisión y cobra sin perder un solo gramo",
    "intro": "Pesaje exacto para tiendas, fruver, carnicerías y bodegas: grameras, básculas con impresión de precios y de piso.",
    "keywords": [
      "báscula digital",
      "báscula digital precio",
      "balanza digital comercial",
      "báscula electrónica con impresión",
      "gramera digital",
      "báscula digital 30kg",
      "báscula electrónica 50kg",
      "balanza gramera",
      "báscula de piso 300kg",
      "báscula ganadera electrónica",
      "báscula digital para negocio",
      "balanza comercial bogotá"
    ],
    "sortOrder": 22
  },
  {
    "slug": "vitrinas-calientes",
    "type": "vitrina-caliente",
    "category": "exhibicion",
    "label": "Vitrinas calientes",
    "eyebrow": "vitrina caliente",
    "h1": "Vitrina caliente exhibidora: mantén pollo, empanadas y pizza listos para vender todo el día",
    "intro": "Exhibe pollo, empanadas, pizza y sushi calientes a la vista del cliente para disparar la compra por impulso.",
    "keywords": [
      "vitrina caliente",
      "vitrina exhibidora caliente",
      "vitrina para comida caliente",
      "vitrina exhibidora de alimentos calientes",
      "vitrina térmica para alimentos",
      "vitrina calefactora",
      "vitrina caliente industrial",
      "vitrina caliente para panadería",
      "vitrina exhibidora caliente precio",
      "vitrina caliente colombia",
      "vitrina para empanadas y pollo",
      "vitrina caliente bogotá"
    ],
    "sortOrder": 23
  },
  {
    "slug": "procesamiento-de-alimentos",
    "type": "procesamiento",
    "category": "procesamiento",
    "label": "Procesamiento de alimentos",
    "eyebrow": "peladora de papas industrial",
    "h1": "Peladoras, tajadoras y laminadoras industriales: procesa papa, pan y masa en minutos y ahorra mano de obra",
    "intro": "Pela, corta, rebana y lamina en minutos: peladoras de papa, tajadoras de pan, laminadoras de masa y procesadores.",
    "keywords": [
      "peladora de papas industrial",
      "pelador de papas industrial",
      "peladora de papas precio",
      "tajadora de pan industrial",
      "cortadora rebanadora de pan",
      "procesador de alimentos industrial",
      "cortadora de vegetales industrial",
      "laminadora de masa",
      "laminadora de masa para pizza",
      "sobadora laminadora panadería",
      "máquina para pasta",
      "vinipeladora",
      "procesador de alimentos precio colombia",
      "laminadora de masa precio"
    ],
    "sortOrder": 24
  },
  {
    "slug": "bano-maria-y-buffet",
    "type": "buffet",
    "category": "buffet",
    "label": "Baño maría y buffet",
    "eyebrow": "baño maría",
    "h1": "Baño maría y samovares para buffet: sirve la comida caliente y presentable en eventos y línea de servicio",
    "intro": "Mantén la comida caliente y presentable en tu línea de servicio: baño maría, samovares y calentadores.",
    "keywords": [
      "baño maría",
      "baño maría eléctrico",
      "baño maría para buffet",
      "calentador de alimentos buffet",
      "samovar para buffet",
      "samovar calentador eléctrico",
      "chafing dish acero inoxidable",
      "baño maría 5 azafates",
      "baño maría precio",
      "samovar precio colombia",
      "baño maría industrial",
      "bandeja antideslizante para buffet"
    ],
    "sortOrder": 25
  },
  {
    "slug": "refrigeracion-comercial",
    "type": "refrigeracion",
    "category": "refrigeracion",
    "label": "Refrigeración comercial",
    "eyebrow": "congelador industrial",
    "h1": "Congeladores y vitrinas refrigeradas comerciales: conserva carne, helados y bebidas sin perder producto",
    "intro": "Conserva la cadena de frío de tu negocio: congeladores, neveras, vitrinas refrigeradas y botelleros.",
    "keywords": [
      "congelador industrial",
      "congelador horizontal",
      "congelador horizontal industrial",
      "congelador tipo isla",
      "congelador vertical industrial",
      "nevera comercial",
      "vitrina refrigerada",
      "vitrina refrigerada multideck",
      "enfriador de bebidas botellero",
      "congelador botellero",
      "refrigerador comercial",
      "congelador industrial precio",
      "nevera industrial bogotá",
      "vitrina refrigerada precio"
    ],
    "sortOrder": 26
  },
  {
    "slug": "mobiliario-en-acero-inoxidable",
    "type": "mobiliario",
    "category": "mobiliario",
    "label": "Mobiliario en acero",
    "eyebrow": "mesa de trabajo en acero inoxidable",
    "h1": "Mesas de trabajo y lavaplatos en acero inoxidable 304: monta una cocina industrial a prueba de uso pesado",
    "intro": "La base de toda cocina profesional: mesas de trabajo, lavaplatos y poceta en acero inoxidable 304.",
    "keywords": [
      "mesa de trabajo en acero inoxidable",
      "mesón en acero inoxidable",
      "mesa de trabajo industrial acero",
      "mesa en acero con lavaplatos",
      "fregadero industrial acero inoxidable",
      "lavaplatos industrial acero 304",
      "mesón con poceta",
      "poceta industrial acero inoxidable",
      "mesa de trabajo acero 304",
      "mesón en acero inoxidable precio",
      "mesa de trabajo cocina industrial bogotá",
      "lavaplatos en acero inoxidable cocina industrial"
    ],
    "sortOrder": 27
  },
  {
    "slug": "equipos-para-carniceria",
    "type": "carnicos",
    "category": "carnicos",
    "label": "Equipos para carnicería",
    "eyebrow": "molino de carne",
    "h1": "Molinos, embutidoras y sierras para carnicería: procesa carne, chorizo y cortes con rendimiento de negocio",
    "intro": "Procesa carne con rendimiento y seguridad: molinos, embutidoras de chorizo y sierras para hueso.",
    "keywords": [
      "molino de carne",
      "molino de carne industrial",
      "moledora de carne",
      "molino de carne #32",
      "molino y embutidora de chorizos",
      "embutidora de chorizos",
      "embutidora de carne",
      "sierra para huesos",
      "sierra corta hueso",
      "asador vertical shawarma",
      "trompo de carne para shawarma",
      "molino de carne precio colombia",
      "embutidora de chorizos precio",
      "clipadora de embutidos"
    ],
    "sortOrder": 28
  }
];
